### PR TITLE
Bugfix and readability improvement

### PR DESCRIPTION
**Pull request by mennohofste**
A combination of small updates I have been testing over the past few days.

This PR includes the removal of `set_pythonpath`, which has been replaced by hooks #81. No users should be negatively affected.

This is not ready to merge yet. I will use this for a few more days. Any feedback is welcome!

### CODE REVIEW

**Comment by mennohofste** [comment]
I have not encountered any changes in behaviour after using it for a while. I think it is ready for review.

**Comment by mennohofste** [comment]
I happen to be reading this comment in the `nvim-lspconfig` repo. https://github.com/neovim/nvim-lspconfig/issues/299#issuecomment-718458638

I think Pylance has not been working outside of VSCode since 2020, so I assume it is safe to remove entirely?

**Comment by linux-cultist** [comment]
Seems to work fine for me also, did a testrun here and didnt notice anything breaking.

And yes, please remove Pylance when you are at it. :)

**Comment by mennohofste** [comment]
I rebased to clean up some commits, and I think it can be merged now if everything looks good. 

I am still looking at a few small things, but those can be added in another PR.

**Comment by mennohofste** [comment]
I just noticed that I forgot to update the documentation. Will do that first.

**Comment by mennohofste** [comment]
Now the docs should also be up-to-date.

**Comment by linux-cultist** [comment]
Ok thank you. What do you say, we merge this in or do you want to add more changes?

**Comment by mennohofste** [comment]
I think you can merge it. 👍

**Pull request merged**
