### PR TITLE
feat(search_venv): add search into project

### PR DESCRIPTION
**Pull request by ulthuan**
Hi again!,
I create this pull request for add the functionality of search into local folder too because the name of the local virtualenv has different name than the global ones.

This functionality add into the list of results the virtualenv (if exists the directory) of the project folder. For the activate of this functionality and the name of the virtualenv inside the project  I created several options.

Other thing that I see was in several parts of the code exists the discover of operating system folder separator. What do you think about creation of utils function that return this separator? If you are ok with this functionality I develop it and create a pull request apart for it.

Thanks for your time and the opportunity of contribute to this project

### CODE REVIEW

**Comment by linux-cultist** [comment]
Hey!

I think its nice, lets add the functionality! We should add the new default parameters to the README.md also. 

But I wanted to ask you, can you create a git branch instead with your changes? It would make it a lot easier to pull down changes locally and test them. It also makes it easier if several people are working on features at the same time. There may be minor merge conflicts to fix but its better than everyone pushing to main I think. I think I will disable pushing to main so we all work in branches.

And yes, totally agree about the operating system separator. I wanted to refactor it also, but didnt have time since we last talked. :) If you want to do it, go ahead and refactor things. Its not just the separator that varies, its also which default path to use for Poetry and Pipenv on different systems. So take that into account when you refactor and add a utility function for returning the default Poetry and Pipenv paths for each operating system (the function can check what OS we are running on).

But please do all this in a separate branch. :) Thank you!

**Comment by ulthuan** [comment]
I think I don't understand you.... I thinked that you referred to upload to this project in a branch, but I don't have permissions to upload a new branch

**Comment by linux-cultist** [comment]
Its ok, I think its me not being used to work in this way with forks. :) I figured out how to pull your PR and add a small fix to it. Lua is a bit weird when checking if directories exists:

https://stackoverflow.com/questions/67259998/neovim-lua-isdirectory-vim-function

So I just modified your code according to the example above. I noticed during my own testing that the local .venv directory would always show up in my listing otherwise (even when it didnt exist on my computer).

I will just add some extra info to the README and then merge this in.

Your english is not bad by the way, I understand you very easily. :)

If you feel like refactoring the code that gives the default paths to Poetry and Pipenv, and other code where os detection is important, feel free to do so. :)

**Comment by ulthuan** [comment]
Ohhh, it's a little weird yes 😓

Thanks for the explanation this is my first adventure in the Lua world jejej (I try to create my own neovim configuration too but it's a different kind of project) and I need to know all that things for do a better code.

Of course! I have the code with the refactor more or less do, when you merge this PR I'll update my fork and review a little more the code before upload.

Thanks for your kind words about my English 😃

**Comment by linux-cultist** [comment]
I noticed some more weirdness with the change, let me try and explain... :)

In the function `VS.search_local_path = function(path)`, the path is actually the current file opened in the buffer when running VenvSelect. So with your change, the code would look for `.venv` only in the same folder as the opened file.

If you would have a file opened that is located in a project subdirectory under your project, and you run `VenvSelector`, it wont find your `.venv` anymore. So this is what the `parents` option is doing - it will look in the parent directories and find your `.venv` there if you set the `name` option to `.venv`.

So what we want is actually that the `name` option will simply be able to take a list of venv names it will look for, and then it will find your venvs even if they have different names under your project directory.

So im thinking that is possibly a better solution, both because we dont need `local_search` and `local_name` anymore, but also because its more future proof. Some users may have 3 or 4 different names on their venvs spread across the system.. :)

What do you think?

**Comment by ulthuan** [comment]
I think that it’s a great option 😃, and as you said cover future users necessities of another name for their virtualenvs

Another option that I thinked it’s get the root dir of the project from the lsp server. If we can get this directory I think that we can use for this special case.

I don’t know if that las option it’s possible or not. What do you think? Try to find it or go better for the other option and search over the array of names?

I’ll glad to implement the option that you think it’s better 😃

**Comment by ulthuan** [comment]
You explained perfectly the problem! Thanks for that and sorry for the bug 😓

I’m agree with the idea of search in the three places. I don’t knew the workspace option and I was thinking to ask to you about to try to use the root directory from the lsp server if we can get from it. But if the workspace option exists we can try first it.

I’ll glad to try to implement this option if you like and update this pull request 😃

**Comment by linux-cultist** [comment]
I was thinking to make a bit bigger change to the plugin and add tests, and as part of that refactor the code so it's easier to test as well. The number of users are growing and the last thing we want is to push changes that break things. As we add more and more functions, it will also be hard to test things manually.

So I think maybe let me make that change first and then we are in a better place to make changes without fear of breaking something.

Sounds alright?

**Comment by ulthuan** [comment]
I think it's a great idea adding tests before appending more functionality to the plugin.

I think that another complementary thing that we can add to offer more reliability is semantic versions. With this the user can have more control of the changes that download with the package manager and also offers us more flexibility to do changes without breaking the user’s editor.

I’ll be glad to help with the testing but at this moment I haven't done it before in neovim. When you have the first tests done I think that I can help to add more 😃

**Comment by linux-cultist** [comment]
Yeah im currently trying to set up testing with lua and neovim also, havent done it before either. :) 

If I get something to work, I will of course share how you can set it up too :)

**Comment by linux-cultist** [comment]
I need some help. :)  if you run the below in command mode in neovim on windows, do you get "Windows"?

`lua print(vim.loop.os_uname().sysname)`

**Comment by ulthuan** [comment]
The command print Windows_NT 😃

**Comment by linux-cultist** [comment]
Wow, Ok! :smile:   Back to the 80's ... 

I added "Windows_NT" to the code along with lots of refactoring efforts in order to make testing separate functions a lot easier later. 

If you have the time and energy, please try the branch called "mostly_refactoring" and see if it works for you. I have really tried to not mess anything up but see if you can find something broken / weird.  Some new things in this branch:

- Multiple venv names in `name` parameter to setup function. If you set a lua table here instead of a simple string, it will look for all your specified names. Example: name = {"venv", ".venv"}. Remember to set parents to 2 or something if you dont want to look only in the same directory as your file.

- I switched to regular expressions for the paths and venv names to look for, to allow fd to only run once instead of once per venv name and once to look for both Pipenv and Poetry folders. So this should also make VenvSelect not match on "venv" in the middle of a path, if it did that before. It needs to be at the end. :)

- Lots of moving code around and making smaller functions, and splitting up the OS detection stuff into utils.

This will also make it a lot easier to add the "look in workspace" functionality" we talked about later. :)

**Comment by linux-cultist** [comment]
I moved a lot of stuff around but I hope you will find it easier rather than harder to understand! The logic is this:

`config.lua` - default settings and user settings
`init.lua` - here it all starts
`system.lua` - code for finding system differences between mac, linux and windows
`telescope.lua` - the user interface part with showing results
`utils.lua` - utility functions
`venv.lua` - code for working with finding / activating venvs.

**Comment by linux-cultist** [comment]
I will close the PR since it's better to use the name setting with many venv names (now that it's supported) rather than add extra options. :)

**Comment by ulthuan** [comment]
I like all the changes in the refactor :). I think that with this change for use client at search the workspace and search on it the project's virtualenv it's the better approach :)

And of course the split of files and the utilities functions add a lot of help on the search of the better code before testing process.

I tested the code on Mac and Windows and the code works well :) I think that we can merge it on the main branch and go for the testing :)

Sorry for the delay on said something :(

**Comment by linux-cultist** [comment]
Hey! 

Its totally fine, I dont expect you or anyone else to feel pressure to contribute if you have other things going on in your life. I will actually myself start a new job next week so time will be more limited to work on the plugin. But I hope by then it doesnt have bugs that break functionality.

Im working on one last thing right now - I would like the current venv to be listed as Active in the list when its selected, instead of having to print out "venv has been activated" in the vim messages.

There are more things you can test if you have time. If you look in the config.lua file, you see some new options you can set:
```
config.default_settings = {
	search = true,
	name = "venv",
	search_workspace = true,
	search_venv_managers = true,
	parents = 2, -- When search is true, go this many directories up from the current opened buffer
	poetry_path = system.get_venv_manager_default_path("Poetry"),
	pipenv_path = system.get_venv_manager_default_path("Pipenv"),
	enable_debug_output = false,
	auto_refresh = true,
}
```

The `auto refresh` option for example, when set to false, will make the plugin not reload the list every time you open it. This makes it really quick to switch venvs that hasnt changed since it doesnt search. You can manually trigger a search of a new location with Ctrl-r when VenvSelect is open.

**Pull request closed without merging**
