### PR TITLE
Look for hatch in correct folder on Mac (Darwin)

### PR DESCRIPTION
**Pull request by tomplast**

### CODE REVIEW

**Comment by tomplast** [comment]
I may have been a little hasty, as it is not working for me either (I thought it did but now I'm not sure). But one thing is sure, the path wasn't correct before. The folder is called "Application Support".

**Comment by linux-cultist** [comment]
I think you are correct, according to docs it should be `~/Library/Application Support/hatch` for the mac (https://hatch.pypa.io/dev/config/hatch/) but I really wish I could look inside that folder to see what it looks like. 

If you get the default hatch search working on mac, we can merge it. :) Its the only system I cant test myself.

**Comment by tomplast** [comment]
Screenshot 2024-06-23 at 17 12 32

I will fiddle with the path escaping to get it work. I'm used to just using backslash space to escape but apparently there's another solution in this case. I will fix it as I need it myself :)

**Comment by linux-cultist** [comment]
Yeah all that path escaping is really frustrating. On windows I have to use 4 slashes to represent 2 slashes since `\` is an escape character in lua.

You can experiment from inside the plugin also by doing `VenvSelect <your command here to list venvs with fd>`, for example `:VenvSelect ls /tmp` as an example. Could be faster to figure out that way since then it actually does gets parsed by lua also.

**Comment by tomplast** [comment]
Apparently 4 backslashes did the trick, at least for me.

Screenshot 2024-06-23 at 17 53 49

**Comment by linux-cultist** [comment]
Very interesting. I didn't think that would be needed on a mac, but if it works, it works. Should we merge it in then, you feel like its working?

**Comment by tomplast** [comment]
> Very interesting. I didn't think that would be needed on a mac, but if it works, it works. Should we merge it in then, you feel like its working?

Well it's working for me at least, way better than before :). Egoistically I want you to merge it so I don't have to have local changes / use my own fork ;).

**Comment by linux-cultist** [comment]
If it works for you, it should work for others too. And the docs are saying that this location is the default one on mac, so.. Let's merge. :)

**Comment by tomplast** [comment]
@linux-cultist Updated the plugin through Lazy, works like a charm. The simple is often the best :). Thank you for merging!

**Comment by linux-cultist** [comment]
Well huge thanks for the PR :)

**Pull request merged**
