### PR TITLE
Anaconda support

### PR DESCRIPTION
**Pull request by Sped0n**

### CODE REVIEW

**Comment by Sped0n** [comment]
fix #30

**Comment by Sped0n** [comment]
works on UNIX, not sure about windows.
## env list
image

## activate env

image

**Comment by linux-cultist** [comment]
Thank you very much for your contribution :) 

I'm on vacation but will be back in a few days, and will review the PR right away. You have a good looking neovim config by the way. 👍

**Comment by linux-cultist** [comment]
I think it looks great, and extra thanks for updating the README as well. :)

Lets get this merged!

**Pull request merged**
