### PR TITLE
Lualine support

### PR DESCRIPTION
**Pull request by jo-project**
I just want to add a simple [lualine](https://github.com/nvim-lualine/lualine.nvim) support.

https://github.com/linux-cultist/venv-selector.nvim/assets/122333339/9f87ad4c-53f6-4c89-a4fa-a7f37438783c

### CODE REVIEW

**Comment by jo-project** [comment]
Usage:
```lua
sections = { lualine_a = { 'venv-selector' } }
```

**Comment by linux-cultist** [comment]
This looks really nice, good work! Lets get it merged.

Can you add a section to the README also when you have time? Otherwise i can do it later.

**Comment by bonryu** [comment]
Thank you!
I'm using LazyVim and this is my `lua/plugins/venv-selector.lua` file, and it works perfectly. The icon is of a tree to denote "environment" and is just a personal touch.
```lua
return {
  {
    "linux-cultist/venv-selector.nvim",
    opts = {
      anaconda_base_path = "~/miniconda3",
      anaconda_envs_path = "~/miniconda3/envs",
    },
  },
  {
    "nvim-lualine/lualine.nvim",
    optional = true,
    event = "VeryLazy",
    opts = function(_, opts)
      table.insert(opts.sections.lualine_x, { "venv-selector", icon = "\u{1f332}", color = { fg = "#7fb55e" } })
    end,
  },
}
```

**Comment by BestChinchilla** [comment]
@linux-cultist Lualine or venv-selector don't print any errors, it's just don't added to status line

venv is activated:

```bash
env | grep -i VIRTUAL_ENV
VIRTUAL_ENV=/tmp/test/.test
```

lazy config for venv-selector:

```lua
return {
  "linux-cultist/venv-selector.nvim",
  dependencies = {
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    "mfussenegger/nvim-dap-python", --optional
    { "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
  },
  lazy = false,
  branch = "regexp", -- This is the regexp branch, use this for the new version
  keys = {
    { "pv", "<cmd>VenvSelect<cr>" },
  },
}
```

lualine config where I declare venv-selector:

```lua
sections = {
          lualine_a = { "mode", "venv-selector" },
          ...
}
```

**Comment by BestChinchilla** [comment]
@linux-cultist I'm complete reinstalled plugin, add regexp branch and command VenvSelect is worked! But I didn't found the lualine integration in source code at that branch and this is why lualine status line don't work  : )
lualine

My neovim plugin file
```lua
return {
  "linux-cultist/venv-selector.nvim",
  dependencies = {
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    "mfussenegger/nvim-dap-python", --optional
    { "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
  },
  lazy = false,
  branch = "regexp", -- This is the regexp branch, use this for the new version
  keys = {
    { "<leader>pv", "<cmd>VenvSelect<cr>" },
  },
  ---@type venv-selector.Config
  opts = {
    -- Your settings go here
  },
}
```

**Comment by linux-cultist** [comment]
Ah yeah, that is possible. :)

It shouldnt be hard to move it over to the new branch. Can create a github issue so we remember it. :+1:

**Pull request merged**
