### PR TITLE
add hidden venvs in workspace path to default config

### PR DESCRIPTION
**Pull request by smorokin**
Some people prefer hiding their virtual env directories.

### CODE REVIEW

**Comment by linux-cultist** [comment]
This is actually again a very good usecase for the new regexp branch of the plugin I'm working on. Since you can write your own fd queries in that one, you can make it work exactly how you need. You can check out the Readme and try the branch if you like. It works well for Linux and Mac users at this point I believe, but more work is ongoing to support windows properly as well.

**Comment by smorokin** [comment]
@linux-cultist  do you think it's a bad idea to have hidden files included by default? I would love to have this, since it would mean that I don't have to configure anything at all.

**Comment by linux-cultist** [comment]
I think maybe the default should not be to force fd to parse hidden files. Often in a workspace, there is a git repository or other hidden files, and then fd would have to go through all of those when looking for venvs. It would make the search slower for everyone who doesn't have hidden venvs.

Sometimes people also have stuff like .vscode or .idea folders with even more hidden files to go through. But that's why the regexp code is written so you can override this behavior how you want. But it does require a bit of config though.

I will add to the Readme how you can override the existing search with your own later today since it's a very good thing to document. :)

**Comment by smorokin** [comment]
Yes, you are right. Especially the `.git` folder is a huge problem. Will wait for the documentation!

**Comment by linux-cultist** [comment]
Its actually really easy to override the build-in searches:

If you look in the https://github.com/linux-cultist/venv-selector.nvim/blob/regexp/lua/venv-selector/config.lua file, you see the default searches.

If you want to override one of them, just create a search with the same name. So to override the workspace search with what you wanted:

```
search = {
            workspace = {
                    command = "fd '/bin/python$' $WORKSPACE_PATH --full-path --color never -E /proc -unrestricted",
                }
}
```

And thats it. :)

**Comment by linux-cultist** [comment]
After thinking about this some more, I changed the default behavior to search for hidden files in current working directory and the workspace dirs. Because even if its slightly slower, its more useful to users if their venvs show up without configuration. And if users feel like the plugin is too slow, they can change the default search very easily. Most will probably be OK with it not being instant. 

So thanks for this idea, appreciate it. :)

**Comment by smorokin** [comment]
Thank you @linux-cultist, it just works now!

P.S.: You could also add  [rye](https://rye-up.com/) to the list of supported package managers.

**Comment by linux-cultist** [comment]
Sure, should be easy to to. Thanks for responding, always nice to get feedback so I know things are working as they should. :)

**Comment by linux-cultist** [comment]
I think rye just creates ordinary venvs under the project directory so they should be found without doing anything. Let me know if you have any issues. :)

**Comment by smorokin** [comment]
Yes, rye works very well with venv-selector. I meant that you could add it to the list so people will see that it is supported.

**Comment by linux-cultist** [comment]
Oh yes, makes sense. :)

**Pull request closed without merging**
