### PR TITLE
fix(#145): delete `user_settings` param.

### PR DESCRIPTION
**Pull request by mochouaaaaa**
This parameter causes the parameter merge not to be completed when `LSP Server` starts up

The project is automatically formatted according to the style configuration in the directory, if you need to keep the original format I will withdraw the change

### CODE REVIEW

**Comment by mochouaaaaa** [comment]
> This parameter causes the parameter merge not to be completed when `LSP Server` starts up
> 
> The project is automatically formatted according to the style configuration in the directory, if you need to keep the original format I will withdraw the change

**Comment by mochouaaaaa** [comment]
I'll test it a bit more and reopen it

**Comment by linux-cultist** [comment]
@mochouaaaaa Sorry for the trouble, but could you format the PR again according to the new `stylua.toml` (i changed it to include parantheses on function calls since its easier to understand for everyone).

**Comment by linux-cultist** [comment]
Im also not sure why you want to remove user_settings. I looked at my code now when im back from vacation, and its a local variable that stores the result from merging the default settings with the users plugin settings:

```
function M.merge_user_settings(user_settings)
    log.debug("User plugin settings: ", user_settings.settings, "")
    M.user_settings = vim.tbl_deep_extend("force", M.default_settings, user_settings.settings or {})

    M.user_settings.detected = {
        system = vim.loop.os_uname().sysname,
    }

    log.debug("Complete user settings:", M.user_settings, "")
end
```

And this is later used everywhere in the plugin to check for what settings the user has specified and make decisions.

I dont understand what you mean with this:

`This parameter causes the parameter merge not to be completed when LSP Server starts up`

Can you explain a bit more?

**Comment by linux-cultist** [comment]
I'm closing this but if you think it's a mistake, just respond to the questions above . Maybe I don't understand something.

**Pull request closed without merging**
