### PR TITLE
Add miniconda venv support

### PR DESCRIPTION
**Pull request by barikata1984**
# What
Find Miniconda `envs` directories set up with the standard installation and make them selectable.

# Why
Some users, including me, prefer Miniconda to Anaconda. Making the venvs created by miniconda selectable as the default behaviour of this plug-in sounds cool.

# How
Just follow how Anaconda `envs` are detected.

# Note
The same approach should work on MacOS and Windows. But, I have not implemented and tested it because I do not have those machines right now.

### CODE REVIEW

**Comment by RobertoRRW** [comment]
Hardcoding the paths runs into the same mistakes that are in the current code. This won't work if using either miniforge or condaforge; or if the user decides to install somewhere other than the default location. All these variations of conda use common environment variables: Base is at `$CONDA_PREFIX/bin` and the envs are at `$CONDA_PREFIX/envs`.

**Comment by barikata1984** [comment]
@RobertoRRW 

Why don't you post an improvement request or make a PR? Hardcoding is the approach this plugin has employed to locate venvs. The objective of this PR is just to add the ability to find miniconda envs without custom configurations

**Comment by RobertoRRW** [comment]
It will only successfully add miniconda envs _if_ they are installed in a specific location, which isn't even the default for conda forge.

**Comment by linux-cultist** [comment]
@RobertoRRW I think the best we can do is let the user define their own searches if the venvs are not in their default location. And that's what the `regexp` version of the plugin adds, besides a general cleanup of code. :)

**Comment by linux-cultist** [comment]
@barikata1984 Thanks a lot for the PR, I will review it in a week since I'm on vacation currently. :)

**Comment by linux-cultist** [comment]
> Hardcoding the paths runs into the same mistakes that are in the current code. This won't work if using either miniforge or mambaforge; or if the user decides to install somewhere other than the default location. All these variations of conda use common environment variables that should be used _instead_ of all these variations of Anaconda, conda, miniconda, etc.
> 
> Base is at `$(dirname $CONDA_EXE)` and the envs are at `$(dirname $CONDA_EXE)/../envs`.

Im back from vacation now and read this a bit more carefully. It would be good to use env variables if they are defined. I dont use conda myself but i assume they are set by some conda command in the shell by the user, and when neovim is opened, they will exist?

We can let this PR add miniconda support and also investigate later if we can use env variables to let the plugin be a bit smarter.

**Comment by linux-cultist** [comment]
@barikata1984 We need to use some common formatting so the PR doesnt look like its changing hundreds of lines of code when its just formatting differences. Let me decide on some formatter we can use that works in most editors and get back to this later.

**Comment by RobertoRRW** [comment]
After this gets merged I can test on the varieties of conda for a follow-up PR. Anaconda and Miniconda are just two of them, and then miniforge and mambaforge are the open source ones. As of right now I've only tested on miniforge.

As for the formatting, you could set up a Github action to do `black --check` (or equivalent). It's free for public repos.

**Comment by barikata1984** [comment]
@linux-cultist, why don't you use stylua? `styluaq.toml` is already included in this repo. Actually, there is no difference in the contents of the TOML between your and 
 my repos. If we use the formatter, the format should be aligned

**Comment by linux-cultist** [comment]
I agree, lets use `stylua.toml`. I made a few changes to the stylua config though since i very much prefer parantheses when calling functions, even though I know lua doesnt need it. But I feel it makes the code more similar to other languages and therefore easier to understand for most people.

@barikata1984 Sorry for the trouble, but could you format your code with the new stylua settings and make a new commit? Then it should be a lot easier to spot what has changed. :)

**Comment by barikata1984** [comment]
@linux-cultist I have updated my code. Can you review it?

**Comment by linux-cultist** [comment]
@barikata1984 I made a few changes since we should use type = "anaconda" also for miniconda, since its essentially sets the same env variables.

Its also used to know what to do when loading a cached venv from disk, so the plugin knows what to do.

If you try the code now, everything should still work as it did before.

I will see what paths is needed on windows and add support for that also while we are at it.

**Comment by barikata1984** [comment]
@linux-cultist, I confirmed the your code working fine. Thank for arranging my code.

For this topic,
> Im back from vacation now and read this a bit more carefully. It would be good to use env variables if they are defined. I dont use conda myself but i assume they are set by some conda command in the shell by the user, and when neovim is opened, they will exist?

The following lines are called in `.zshrc` in my case:
```sh
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/atsushi/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/atsushi/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/atsushi/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/atsushi/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
## <<< conda initialize <<<
```
And inside `conda.sh`, `CONDA_EXE` is registered. Since it is in a `.*rc` file, the env var should be registered to each neovim terminal when it is spawned.

**Comment by linux-cultist** [comment]
It would be nice if the plugin could check for `CONDA_EXE` if it is defined. But need to look into it a bit more, so will be some future feature maybe. :)

**Pull request merged**
